### ISSUE TITLE
args not defined

### ISSUE THREAD

**Issue by niosus** [niosus/test-complete-plugin#2]
As reported by @mehdidou99

> DIR!!! =  D:\Programmes\LLVM\bin
> platform:  ('64bit', 'WindowsPE')
> python version:  3.5.1
> filename =  D:\Programmes\LLVM\bin\libclang.dll
> Traceback (most recent call last):
>   File ".\script.py", line 23, in <module>
>     compl_obj = tu.codeComplete(path=filename, args=clang_flags, line=4
> TypeError: codeComplete() got an unexpected keyword argument 'args'

**Comment by niosus** [comment]
This was due to my stupid mistake and should be fixed now as of commit a0d7b0048e1ee2c2e0794d193d9f657c9c5a1db5 

Can you try to run everything again @mehdidou99 ?

**Comment by niosus** [comment]
Should be fixed now, So I will close this one for now. Please reopen should this still be happening.

**Comment by mehdidou99** [comment]
The output seems to be normal, but I post it to be sure : 

> DIR!!! =  D:\Programmes\LLVM\bin
> platform:  ('64bit', 'WindowsPE')
> python version:  3.5.1
> filename =  D:\Programmes\LLVM\bin\libclang.dll
> 59
> 59

**Comment by niosus** [comment]
Yep, it is the expected output, which means that you have 59 completions ready. Exactly the number as I have. So it means that at least you can exactly reproduce the problem, which is already cool :)
